name: Build
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Gradle build
        env:
          GRADLE_CLI_OPTS: ""
        run: "chmod +x ./gradlew && ./gradlew ${GRADLE_CLI_OPTS} build"
